version: '3.10'

services:
  nginx:
    build:
      context: .
      dockerfile: deploy/Dockerfile.nginx
    image: nginx:1.23.2-alpine
    network_mode: host
    volumes:
      - ./deploy/nginx:/etc/nginx/conf.d
      - ./image_object_detector/static:/app/static

  app:
    build: .
    restart: always
    ports:
      - "5005:5005"
