name: Test

on:
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    name: Run Test check
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
    - name: Testing django code
      run: |
        pwd
        ls
        ./script/run_tests.sh
